version: '3'

services:
  app:
    build: .docker/nest
    entrypoint: ./.docker/nest/entrypoint.sh
    container_name: nest-moveit
    ports:
      - 3333:3333
    volumes:
      - ./nestjs-moveit:/home/node/app
  
  db:
    build: .docker/postgres
    restart: always
    tty: trues
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dbnestjs

  front:
    build: .docker/react
    entrypoint: ./.docker/react/entrypoint.sh
    container_name: react-moveit
    ports: 
      - 3000:3000
    volumes: 
        - ./react-moveit:/home/node/app